import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createRef } from 'react'
import ReactToPdf from 'react-to-pdf'
export default function Home() {
  const pdfRef = createRef()

  return (
    <div className={styles.container}>
      <Head>
        <title>React to PDF</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>將下面內容透過 React-to-pdf 套件轉成 PDF 檔</h1>
        <div>
          <ReactToPdf targetRef={pdfRef} filename='div-blue.pdf'>
            {({ toPdf }) => <button onClick={toPdf}>Generate pdf</button>}
          </ReactToPdf>
          <div style={{ width: 500, height: 500, background: 'blue' }} ref={pdfRef}>
            <h1>MUI Table</h1>
            <h2>Start editing to see some magic happen!</h2>
          </div>
        </div>
      </main>
    </div>
  )
}
