import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { createRef } from 'react'
import ReactToPdf from 'react-to-pdf'
import { Button, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper } from '@mui/material'
import styled from 'styled-components'
const ReactToPDFContainer = styled.div`
  width: 100%;
`

function createData(name, calories, fat, carbs, protein) {
  return { name, calories, fat, carbs, protein }
}

const rows = [
  createData('Frozen yoghurt', 159, 6.0, 24, 4.0),
  createData('Ice cream sandwich', 237, 9.0, 37, 4.3),
  createData('Eclair', 262, 16.0, 24, 6.0),
  createData('Cupcake', 305, 3.7, 67, 4.3),
  createData('Gingerbread', 356, 16.0, 49, 3.9),
]

export default function ReactToPDF() {
  const pdfRef = createRef()

  function renderMuiTableView() {
    return (
      <TableContainer component={Paper}>
        <Table sx={{ minWidth: 650 }} aria-label='simple table'>
          <TableHead>
            <TableRow>
              <TableCell>Dessert (100g serving)</TableCell>
              <TableCell align='right'>Calories</TableCell>
              <TableCell align='right'>Fat&nbsp;(g)</TableCell>
              <TableCell align='right'>Carbs&nbsp;(g)</TableCell>
              <TableCell align='right'>Protein&nbsp;(g)</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {rows.map((row) => (
              <TableRow key={row.name} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                <TableCell component='th' scope='row'>
                  {row.name}
                </TableCell>
                <TableCell align='right'>{row.calories}</TableCell>
                <TableCell align='right'>{row.fat}</TableCell>
                <TableCell align='right'>{row.carbs}</TableCell>
                <TableCell align='right'>{row.protein}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>React to PDF</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>將下面內容透過 React-to-pdf 套件轉成 PDF 檔</h1>
        <div>
          <ReactToPdf targetRef={pdfRef} filename='muiTable.pdf'>
            {({ toPdf }) => (
              <Button variant='contained' onClick={toPdf}>
                產生PDF (Generate pdf)
              </Button>
            )}
          </ReactToPdf>
          <ReactToPDFContainer ref={pdfRef}>
            <h1>MUI Table</h1>
            {renderMuiTableView()}
          </ReactToPDFContainer>
        </div>
      </main>
    </div>
  )
}
