import Head from 'next/head'
import { Document, Page, pdfjs } from 'react-pdf'
import styled from 'styled-components'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import dynamic from 'next/dynamic'
// https://github.com/wojtekmaj/react-pdf/issues/136#issuecomment-405393139
// 透過 dynamic import 上設定 ssr 為 false 解決 browser api 在 node 環境下不支援問題。
const PDFViewer = dynamic(import('../src/components/pdf/PDFViewer'), { ssr: false })

// 參考文件：https://www.npmjs.com/package/react-pdf
function ReactPdfRender() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React render PDF</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PDFViewer />
    </div>
  )
}
export default ReactPdfRender
